services:
  consumer-a:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: consumer-a
    environment:
      - DOTNET_ENVIRONMENT=${DOTNET_ENVIRONMENT}
      - Serilog__WriteTo__1__Args__endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - ConnectionStrings__Postgres=${POSTGRES_CONNECTION_STRING}
      - KafkaOptions__Host=${KAFKA_HOST}
    networks:
      - rscore-network

  consumer-b:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: consumer-b
    environment:
      - DOTNET_ENVIRONMENT=${DOTNET_ENVIRONMENT}
      - Serilog__WriteTo__1__Args__endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - ConnectionStrings__Postgres=${POSTGRES_CONNECTION_STRING}
      - KafkaOptions__Host=${KAFKA_HOST}
    networks:
      - rscore-network

  consumer-c:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: consumer-c
    environment:
      - DOTNET_ENVIRONMENT=${DOTNET_ENVIRONMENT}
      - Serilog__WriteTo__1__Args__endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - ConnectionStrings__Postgres=${POSTGRES_CONNECTION_STRING}
      - KafkaOptions__Host=${KAFKA_HOST}
    networks:
      - rscore-network

networks:
  rscore-network:
    name: rscore-network
    driver: bridge