services:
  consumer-match-event-a:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: consumer-match-event-a
    environment:
      - DOTNET_ENVIRONMENT=${DOTNET_ENVIRONMENT}
      - Serilog__WriteTo__1__Args__endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - ConnectionStrings__Postgres=${POSTGRES_CONNECTION_STRING}
      - KafkaOptions__Host=${KAFKA_HOST}
      - OpenTelemetryOptions__Endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT}
    networks:
      - rscore-network

  consumer-match-event-b:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: consumer-match-event-b
    environment:
      - DOTNET_ENVIRONMENT=${DOTNET_ENVIRONMENT}
      - Serilog__WriteTo__1__Args__endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - ConnectionStrings__Postgres=${POSTGRES_CONNECTION_STRING}
      - KafkaOptions__Host=${KAFKA_HOST}
      - OpenTelemetryOptions__Endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT}
    networks:
      - rscore-network

networks:
  rscore-network:
    name: rscore-network
    driver: bridge